version: '3.9'
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
      - ./:/backend
      - /backend/node_modules
      - /backend/vendor
    restart: always
    ports:
      - 5172:5172
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    restart: always
